package ysyx_26030103.common
import chisel3._
import chisel3.util._

object ysyx_26030103_StageConnect {
  def apply[T <: Data](
      Left: DecoupledIO[T],
      Right: DecoupledIO[T]
  ): Unit = apply(Left, Right, false.B, false.B)

  def apply[T <: Data](
      Left: DecoupledIO[T],
      Right: DecoupledIO[T],
      flush: Bool
  ): Unit = apply(Left, Right, flush, flush)

  def apply[T <: Data](
      Left: DecoupledIO[T],
      Right: DecoupledIO[T],
      flush: Bool,
      flushCurrent: Bool
  ): Unit = {
    val BitsReg = Reg(chiselTypeOf(Left.bits))
    val ValidReg = RegInit(false.B)
    val CanAdvance = !ValidReg || Right.ready
    Left.ready := CanAdvance || flush
    // Most boundaries suppress the current output while flushing.  A boundary
    // whose flush is generated by that current output (EXU redirect) must keep
    // the current instruction visible until it fires.  flushCurrent is the
    // explicit kill-current event and must imply flush; keeping it independent
    // of a self-generated redirect also avoids a combinational valid loop.
    Right.valid := ValidReg && !flushCurrent
    Right.bits := BitsReg
    assert(!flushCurrent || flush, "StageConnect flushCurrent must imply flush")
    when(flush) {
      // Never load a younger Left item on a flush.  A preserved current item is
      // cleared only after the downstream actually accepts it.
      when(flushCurrent || Right.fire) {
        ValidReg := false.B
      }
    }.elsewhen(CanAdvance) {
      ValidReg := Left.valid
      when(Left.valid) { BitsReg := Left.bits }
    }
  }
}
