package ysyx_26030103
import chisel3._

class ysyx_26030103_IO extends Bundle {
  val interrupt = Input(Bool())
  // 仿真 ABI 的 custom-0 halt 提交脉冲；不是架构异常/EBREAK 指示。
  val trap_valid = Output(Bool())
  val trap_pc = Output(UInt(32.W))
//写地址的
  val master_awready = Input(Bool())
  val master_awvalid = Output(Bool())
  val master_awaddr = Output(UInt(32.W))
  val master_awid = Output(UInt(4.W))
  val master_awlen = Output(UInt(8.W))
  val master_awsize = Output(UInt(3.W))
  val master_awburst = Output(UInt(2.W))
  val master_awlock = Output(Bool())
  val master_awcache = Output(UInt(4.W))
  val master_awprot = Output(UInt(3.W))
  val master_awqos = Output(UInt(4.W))
//W写的
  val master_wready = Input(Bool())
  val master_wvalid = Output(Bool())
  val master_wdata = Output(UInt(32.W))
  val master_wstrb = Output(UInt(4.W))
  val master_wlast = Output(Bool())
//B写回的
  val master_bready = Output(Bool())
  val master_bvalid = Input(Bool())
  val master_bresp = Input(UInt(2.W))
  val master_bid = Input(UInt(4.W))
//AR的
  val master_arready = Input(Bool())
  val master_arvalid = Output(Bool())
  val master_araddr = Output(UInt(32.W))
  val master_arid = Output(UInt(4.W))
  val master_arlen = Output(UInt(8.W))
  val master_arsize = Output(UInt(3.W))
  val master_arburst = Output(UInt(2.W))
  val master_arlock = Output(Bool())
  val master_arcache = Output(UInt(4.W))
  val master_arprot = Output(UInt(3.W))
  val master_arqos = Output(UInt(4.W))
//R读数据通道
  val master_rready = Output(Bool())
  val master_rvalid = Input(Bool())
  val master_rresp = Input(UInt(2.W))
  val master_rdata = Input(UInt(32.W))
  val master_rlast = Input(Bool())
  val master_rid = Input(UInt(4.W))
//写地址的
  val slave_awready = Output(Bool())
  val slave_awvalid = Input(Bool())
  val slave_awaddr = Input(UInt(32.W))
  val slave_awid = Input(UInt(4.W))
  val slave_awlen = Input(UInt(8.W))
  val slave_awsize = Input(UInt(3.W))
  val slave_awburst = Input(UInt(2.W))
  val slave_awlock = Input(Bool())
  val slave_awcache = Input(UInt(4.W))
  val slave_awprot = Input(UInt(3.W))
  val slave_awqos = Input(UInt(4.W))
//写
  val slave_wready = Output(Bool())
  val slave_wvalid = Input(Bool())
  val slave_wdata = Input(UInt(32.W))
  val slave_wstrb = Input(UInt(4.W))
  val slave_wlast = Input(Bool())
//对面的
  val slave_bready = Input(Bool())
  val slave_bvalid = Output(Bool())
  val slave_bresp = Output(UInt(2.W))
  val slave_bid = Output(UInt(4.W))

  val slave_arready = Output(Bool())
  val slave_arvalid = Input(Bool())
  val slave_araddr = Input(UInt(32.W))
  val slave_arid = Input(UInt(4.W))
  val slave_arlen = Input(UInt(8.W))
  val slave_arsize = Input(UInt(3.W))
  val slave_arburst = Input(UInt(2.W))
  val slave_arlock = Input(Bool())
  val slave_arcache = Input(UInt(4.W))
  val slave_arprot = Input(UInt(3.W))
  val slave_arqos = Input(UInt(4.W))

  val slave_rready = Input(Bool())
  val slave_rvalid = Output(Bool())
  val slave_rresp = Output(UInt(2.W))
  val slave_rdata = Output(UInt(32.W))
  val slave_rlast = Output(Bool())
  val slave_rid = Output(UInt(4.W))
  // 给sdb用的
  val debug_gpr_raddr = Input(UInt(5.W))
  val debug_gpr_rdata = Output(UInt(32.W))
  // debug_pc 是本次退休指令的 PC，只能在 debug_commit 时使用。
  val debug_pc = Output(UInt(32.W))
  // debug_next_pc 与退休记录同拍；debug_arch_pc 是调试器应向
  // 用户展示的最新架构 PC（也会跟踪 trap 跳转）。
  val debug_next_pc = Output(UInt(32.W))
  val debug_arch_pc = Output(UInt(32.W))
  val debug_instructions = Output(UInt(32.W))
  // 内存访问跟踪
  val debug_mtrace_valid = Output(Bool())
  val debug_mtrace_pc = Output(UInt(32.W))
  val debug_mtrace_wen = Output(Bool())
  val debug_mtrace_addr = Output(UInt(32.W))
  val debug_mtrace_wdata = Output(UInt(32.W))
  val debug_mtrace_rdata = Output(UInt(32.W))
  val debug_mtrace_width = Output(UInt(2.W))
  // 访问错误
  val debug_access_fault = Output(Bool())
  val debug_access_fault_pc = Output(UInt(32.W))
  val debug_access_fault_resp = Output(UInt(2.W))
  val debug_commit = Output(Bool())
  val debug_trap_valid = Output(Bool())
  val debug_trap_pc = Output(UInt(32.W))
  val debug_trap_target = Output(UInt(32.W))
  val debug_trap_cause = Output(UInt(32.W))
  // 与 retire/trap 事件分别对齐的 CSR 快照。两组不能共用，
  // 因为同拍可能同时有更老的 WBU 退休与年轻 trap。
  val debug_csr_mstatus = Output(UInt(32.W))
  val debug_csr_mtvec = Output(UInt(32.W))
  val debug_csr_mepc = Output(UInt(32.W))
  val debug_csr_mcause = Output(UInt(32.W))
  val debug_trap_mstatus = Output(UInt(32.W))
  val debug_trap_mtvec = Output(UInt(32.W))
  val debug_trap_mepc = Output(UInt(32.W))
  val debug_trap_mcause = Output(UInt(32.W))
  // 性能计数器
  val perf_ifu_fetch = Output(Bool())
  val perf_exu_done = Output(Bool())
  val perf_lsu_load = Output(Bool())
  val perf_lsu_store = Output(Bool())
  val perf_alu_op = Output(Bool())
  val perf_mem_op = Output(Bool())
  val perf_csr_op = Output(Bool())
  val perf_branch_op = Output(Bool())
  val perf_jal_op = Output(Bool())
  val perf_jalr_op = Output(Bool())
  val perf_mdu_req = Output(Bool())
  val perf_mdu_done = Output(Bool())
  val perf_mdu_op = Output(UInt(3.W))
  val perf_exu_event_kind = Output(UInt(3.W))
  val perf_mdu_active = Output(Bool())
  val perf_mdu_wait = Output(Bool())
  val perf_ifu_stall_pipeline = Output(Bool())
  val perf_ifu_stall_axi = Output(Bool())
  val perf_ifu_stall_ar = Output(Bool())
  val perf_ifu_stall_r = Output(Bool())
  val perf_ifu_stall_redirect = Output(Bool())
  val perf_ifu_stall_idle = Output(Bool())
  val perf_icache_hit = Output(Bool())
  val perf_icache_miss = Output(Bool())
  val perf_dcache_hit = Output(Bool())
  val perf_dcache_miss = Output(Bool())
  val perf_dcache_refill_req = Output(Bool())
  val perf_dcache_refill_resp = Output(Bool())
  val perf_execution_active = Output(Bool())
  val perf_exu_stall_lsu = Output(Bool())
  val perf_lsu_active = Output(Bool())
  val perf_lsu_load_active = Output(Bool())
  val perf_lsu_store_active = Output(Bool())
  val perf_lsu_stall_read_ar = Output(Bool())
  val perf_lsu_stall_read_r = Output(Bool())
  val perf_lsu_stall_write_req = Output(Bool())
  val perf_lsu_stall_write_b = Output(Bool())
  val perf_idu_stall_raw = Output(Bool())
  val perf_idu_stall_raw_loaduse = Output(Bool())
  val perf_idu_stall_raw_alu = Output(Bool())
  val perf_exu_idle_noinput = Output(Bool())
  val perf_trap = Output(Bool())
  val perf_mem_waitslot = Output(Bool())

}
