package ysyx_26030103
import chisel3._

class ysyx_26030103_IO extends Bundle {
  val interrupt = Input(Bool())
  val trap_valid = Output(Bool())
  val trap_pc = Output(UInt(32.W))
//写地址的
  val master_awready = Input(Bool())
  val master_awvalid = Output(Bool())
  val master_awaddr = Output(UInt(32.W))
  val master_awid = Output(UInt(4.W))
  val master_awlen = Output(UInt(8.W))
  val master_awsize = Output(UInt(3.W))
  val master_awburst = Output(UInt(2.W))
  val master_awlock = Output(Bool())
  val master_awcache = Output(UInt(4.W))
  val master_awprot = Output(UInt(3.W))
  val master_awqos = Output(UInt(4.W))
//W写的
  val master_wready = Input(Bool())
  val master_wvalid = Output(Bool())
  val master_wdata = Output(UInt(32.W))
  val master_wstrb = Output(UInt(4.W))
  val master_wlast = Output(Bool())
//B写回的
  val master_bready = Output(Bool())
  val master_bvalid = Input(Bool())
  val master_bresp = Input(UInt(2.W))
  val master_bid = Input(UInt(4.W))
//AR的
  val master_arready = Input(Bool())
  val master_arvalid = Output(Bool())
  val master_araddr = Output(UInt(32.W))
  val master_arid = Output(UInt(4.W))
  val master_arlen = Output(UInt(8.W))
  val master_arsize = Output(UInt(3.W))
  val master_arburst = Output(UInt(2.W))
  val master_arlock = Output(Bool())
  val master_arcache = Output(UInt(4.W))
  val master_arprot = Output(UInt(3.W))
  val master_arqos = Output(UInt(4.W))
//R
  val master_rready = Output(Bool())
  val master_rvalid = Input(Bool())
  val master_rresp = Input(UInt(2.W))
  val master_rdata = Input(UInt(32.W))
  val master_rlast = Input(Bool())
  val master_rid = Input(UInt(4.W))
//写地址的
  val slave_awready = Output(Bool())
  val slave_awvalid = Input(Bool())
  val slave_awaddr = Input(UInt(32.W))
  val slave_awid = Input(UInt(4.W))
  val slave_awlen = Input(UInt(8.W))
  val slave_awsize = Input(UInt(3.W))
  val slave_awburst = Input(UInt(2.W))
  val slave_awlock = Input(Bool())
  val slave_awcache = Input(UInt(4.W))
  val slave_awprot = Input(UInt(3.W))
  val slave_awqos = Input(UInt(4.W))
//写
  val slave_wready = Output(Bool())
  val slave_wvalid = Input(Bool())
  val slave_wdata = Input(UInt(32.W))
  val slave_wstrb = Input(UInt(4.W))
  val slave_wlast = Input(Bool())
//对面的
  val slave_bready = Input(Bool())
  val slave_bvalid = Output(Bool())
  val slave_bresp = Output(UInt(2.W))
  val slave_bid = Output(UInt(4.W))

  val slave_arready = Output(Bool())
  val slave_arvalid = Input(Bool())
  val slave_araddr = Input(UInt(32.W))
  val slave_arid = Input(UInt(4.W))
  val slave_arlen = Input(UInt(8.W))
  val slave_arsize = Input(UInt(3.W))
  val slave_arburst = Input(UInt(2.W))
  val slave_arlock = Input(Bool())
  val slave_arcache = Input(UInt(4.W))
  val slave_arprot = Input(UInt(3.W))
  val slave_arqos = Input(UInt(4.W))

  val slave_rready = Input(Bool())
  val slave_rvalid = Output(Bool())
  val slave_rresp = Output(UInt(2.W))
  val slave_rdata = Output(UInt(32.W))
  val slave_rlast = Output(Bool())
  val slave_rid = Output(UInt(4.W))
  // 给sdb用的
  val debug_gpr_raddr = Input(UInt(5.W))
  val debug_gpr_rdata = Output(UInt(32.W))
  val debug_pc = Output(UInt(32.W))
  val debug_instructions = Output(UInt(32.W))
  // mtrace
  val debug_mtrace_valid = Output(Bool())
  val debug_mtrace_wen   = Output(Bool())
  val debug_mtrace_addr  = Output(UInt(32.W))
  val debug_mtrace_wdata = Output(UInt(32.W))
  val debug_mtrace_rdata = Output(UInt(32.W))
  val debug_mtrace_width = Output(UInt(2.W))
  // Access Fault
  val debug_access_fault = Output(Bool())
  val debug_access_fault_resp = Output(UInt(2.W))
  val debug_commit = Output(Bool())
  // 性能计数器
  val perf_ifu_fetch  = Output(Bool())
  val perf_exu_done   = Output(Bool())
  val perf_lsu_load   = Output(Bool())
  val perf_lsu_store  = Output(Bool())
  val perf_alu_op     = Output(Bool())
  val perf_mem_op     = Output(Bool())
  val perf_csr_op     = Output(Bool())
  val perf_branch_op  = Output(Bool())
  val perf_ifu_stall_pipeline = Output(Bool())
  val perf_ifu_stall_axi      = Output(Bool())
  val perf_ifu_stall_ar       = Output(Bool())
  val perf_ifu_stall_r        = Output(Bool())
  val perf_ifu_stall_redirect = Output(Bool())
  val perf_ifu_stall_idle     = Output(Bool())
  val perf_icache_hit         = Output(Bool())
  val perf_icache_miss        = Output(Bool())
  val perf_execution_active   = Output(Bool())
  val perf_exu_stall_lsu      = Output(Bool())
  val perf_lsu_active         = Output(Bool())
  val perf_lsu_load_active    = Output(Bool())
  val perf_lsu_store_active   = Output(Bool())
  val perf_lsu_stall_read_ar  = Output(Bool())
  val perf_lsu_stall_read_r   = Output(Bool())
  val perf_lsu_stall_write_req = Output(Bool())
  val perf_lsu_stall_write_b  = Output(Bool())
  val semihost_valid = Output(Bool())
  val semihost_char  = Output(UInt(8.W))
}
