file(STRINGS "${AUTO_CONF}" _lines)
foreach(_line ${_lines})
    string(STRIP "${_line}" _line)
    if(_line MATCHES "^#" OR _line STREQUAL "")
        continue()
    endif()
    if(_line MATCHES "^([^=]+)=(.*)$")
        set(_key "${CMAKE_MATCH_1}")
        set(_val "${CMAKE_MATCH_2}")
        string(REPLACE "\"" "" _val "${_val}")
        set(${_key} "${_val}" CACHE INTERNAL "")
    endif()
endforeach()

# 将 CONFIG_CACHE_* 映射为不带 CONFIG_ 前缀的变量供 -D 使用
foreach(_var CACHE_BLOCK_SIZE CACHE_NUM_BLOCKS CACHE_WAYS REPL_POLICY)
    if(DEFINED CONFIG_${_var})
        set(${_var} "${CONFIG_${_var}}" CACHE STRING "")
    endif()
endforeach()

# 默认值
if(NOT DEFINED CACHE_BLOCK_SIZE)
    set(CACHE_BLOCK_SIZE 4 CACHE STRING "")
endif()
if(NOT DEFINED CACHE_NUM_BLOCKS)
    set(CACHE_NUM_BLOCKS 16 CACHE STRING "")
endif()
if(NOT DEFINED CACHE_WAYS)
    set(CACHE_WAYS 1 CACHE STRING "")
endif()
if(NOT DEFINED REPL_POLICY)
    set(REPL_POLICY 0 CACHE STRING "")
endif()
