file(STRINGS "${AUTO_CONF}" _lines)
foreach(_line ${_lines})
    string(STRIP "${_line}" _line)
    if(_line MATCHES "^#" OR _line STREQUAL "")
        continue()
    endif()
    if(_line MATCHES "^([^=]+)=(.*)$")
        set(_key "${CMAKE_MATCH_1}")
        set(_val "${CMAKE_MATCH_2}")
        string(REPLACE "\"" "" _val "${_val}")
        set(${_key} "${_val}" CACHE INTERNAL "")
    endif()
endforeach()