/* verilator lint_off PINMISSING */
module riscv32e_npc_SimTop(
  input         clock,
  input         reset,
  output        trap_valid,
  output [31:0] trap_pc,
  input  [4:0]  debug_gpr_raddr,
  output [31:0] debug_gpr_rdata,
  output [31:0] debug_pc,
  output [31:0] debug_instructions,
  output        debug_mtrace_valid,
  output        debug_mtrace_wen,
  output [31:0] debug_mtrace_addr,
  output [31:0] debug_mtrace_wdata,
  output [31:0] debug_mtrace_rdata,
  output [1:0]  debug_mtrace_width,
  output        debug_access_fault,
  output [1:0]  debug_access_fault_resp,
  output        debug_commit,
  output perf_ifu_fetch, perf_exu_done, perf_lsu_load, perf_lsu_store,
  output perf_alu_op, perf_mem_op, perf_csr_op, perf_branch_op,
  output perf_jal_op, perf_jalr_op,
  output perf_ifu_stall_pipeline, perf_ifu_stall_axi, perf_ifu_stall_ar, perf_ifu_stall_r,
  output perf_ifu_stall_redirect, perf_ifu_stall_idle,
  output perf_execution_active, perf_exu_stall_lsu, perf_lsu_active,
  output perf_lsu_load_active, perf_lsu_store_active,
  output perf_lsu_stall_read_ar, perf_lsu_stall_read_r,
  output perf_lsu_stall_write_req, perf_lsu_stall_write_b,
  output perf_icache_hit, perf_icache_miss,
  output perf_mem_waitslot
);

  wire        cpu_awready, cpu_awvalid, cpu_wready, cpu_wvalid, cpu_wlast;
  wire [31:0] cpu_awaddr, cpu_wdata;
  wire [3:0]  cpu_wstrb;
  wire        cpu_bready, cpu_bvalid;
  wire [1:0]  cpu_bresp;
  wire [3:0]  cpu_bid, cpu_rid;
  wire        cpu_arready, cpu_arvalid, cpu_rready, cpu_rvalid, cpu_rlast;
  wire [31:0] cpu_araddr, cpu_rdata;
  wire [1:0]  cpu_rresp;

  ysyx_26030103 cpu (
    .clock(clock), .reset(reset),
    .io_interrupt(1'b0),
    .io_trap_valid(trap_valid), .io_trap_pc(trap_pc),
    .io_master_awready(cpu_awready), .io_master_awvalid(cpu_awvalid),
    .io_master_awaddr(cpu_awaddr),
    .io_master_awid(), .io_master_awlen(), .io_master_awsize(), .io_master_awburst(),
    .io_master_awlock(), .io_master_awcache(), .io_master_awprot(), .io_master_awqos(),
    .io_master_wready(cpu_wready), .io_master_wvalid(cpu_wvalid),
    .io_master_wdata(cpu_wdata), .io_master_wstrb(cpu_wstrb), .io_master_wlast(cpu_wlast),
    .io_master_bready(cpu_bready), .io_master_bvalid(cpu_bvalid),
    .io_master_bresp(cpu_bresp), .io_master_bid(),
    .io_master_arready(cpu_arready), .io_master_arvalid(cpu_arvalid),
    .io_master_araddr(cpu_araddr),
    .io_master_arid(), .io_master_arlen(), .io_master_arsize(), .io_master_arburst(),
    .io_master_arlock(), .io_master_arcache(), .io_master_arprot(), .io_master_arqos(),
    .io_master_rready(cpu_rready), .io_master_rvalid(cpu_rvalid),
    .io_master_rdata(cpu_rdata), .io_master_rresp(cpu_rresp),
    .io_master_rlast(cpu_rlast), .io_master_rid(),
    .io_slave_awready(), .io_slave_awvalid(1'b0),
    .io_slave_awaddr(32'b0), .io_slave_awid(4'b0), .io_slave_awlen(8'b0),
    .io_slave_awsize(3'b0), .io_slave_awburst(2'b0), .io_slave_awlock(1'b0),
    .io_slave_awcache(4'b0), .io_slave_awprot(3'b0), .io_slave_awqos(4'b0),
    .io_slave_wready(), .io_slave_wvalid(1'b0),
    .io_slave_wdata(32'b0), .io_slave_wstrb(4'b0), .io_slave_wlast(1'b0),
    .io_slave_bready(1'b0), .io_slave_bvalid(), .io_slave_bresp(), .io_slave_bid(),
    .io_slave_arready(), .io_slave_arvalid(1'b0),
    .io_slave_araddr(32'b0), .io_slave_arid(4'b0), .io_slave_arlen(8'b0),
    .io_slave_arsize(3'b0), .io_slave_arburst(2'b0), .io_slave_arlock(1'b0),
    .io_slave_arcache(4'b0), .io_slave_arprot(3'b0), .io_slave_arqos(4'b0),
    .io_slave_rready(1'b0), .io_slave_rvalid(), .io_slave_rresp(),
    .io_slave_rdata(), .io_slave_rlast(), .io_slave_rid(),
    .io_debug_gpr_raddr(debug_gpr_raddr), .io_debug_gpr_rdata(debug_gpr_rdata),
    .io_debug_pc(debug_pc), .io_debug_instructions(debug_instructions),
    .io_debug_mtrace_valid(debug_mtrace_valid),
    .io_debug_mtrace_wen(debug_mtrace_wen),
    .io_debug_mtrace_addr(debug_mtrace_addr),
    .io_debug_mtrace_wdata(debug_mtrace_wdata),
    .io_debug_mtrace_rdata(debug_mtrace_rdata),
    .io_debug_mtrace_width(debug_mtrace_width),
    .io_debug_access_fault(debug_access_fault),
    .io_debug_access_fault_resp(debug_access_fault_resp),
    .io_debug_commit(debug_commit),
    .io_perf_ifu_fetch(perf_ifu_fetch), .io_perf_exu_done(perf_exu_done),
    .io_perf_lsu_load(perf_lsu_load), .io_perf_lsu_store(perf_lsu_store),
    .io_perf_alu_op(perf_alu_op), .io_perf_mem_op(perf_mem_op),
    .io_perf_csr_op(perf_csr_op), .io_perf_branch_op(perf_branch_op),
    .io_perf_jal_op(perf_jal_op), .io_perf_jalr_op(perf_jalr_op),
    .io_perf_ifu_stall_pipeline(perf_ifu_stall_pipeline),
    .io_perf_ifu_stall_axi(perf_ifu_stall_axi),
    .io_perf_ifu_stall_ar(perf_ifu_stall_ar), .io_perf_ifu_stall_r(perf_ifu_stall_r),
    .io_perf_ifu_stall_redirect(perf_ifu_stall_redirect),
    .io_perf_ifu_stall_idle(perf_ifu_stall_idle),
    .io_perf_execution_active(perf_execution_active),
    .io_perf_exu_stall_lsu(perf_exu_stall_lsu),
    .io_perf_lsu_active(perf_lsu_active),
    .io_perf_lsu_load_active(perf_lsu_load_active),
    .io_perf_lsu_store_active(perf_lsu_store_active),
    .io_perf_lsu_stall_read_ar(perf_lsu_stall_read_ar),
    .io_perf_lsu_stall_read_r(perf_lsu_stall_read_r),
    .io_perf_lsu_stall_write_req(perf_lsu_stall_write_req),
    .io_perf_lsu_stall_write_b(perf_lsu_stall_write_b),
    .io_perf_icache_hit(perf_icache_hit), .io_perf_icache_miss(perf_icache_miss),
    .io_perf_mem_waitslot(perf_mem_waitslot)
  );

  riscv32e_npc_AXIRAM ram (
    .clock(clock), .reset(reset),
    .io_axi_AW_AWVALID(cpu_awvalid), .io_axi_AW_AWREADY(cpu_awready),
    .io_axi_AW_AWADDR(cpu_awaddr),
    .io_axi_AW_AWID(4'b0), .io_axi_AW_AWLEN(8'b0), .io_axi_AW_AWSIZE(3'b0),
    .io_axi_AW_AWBURST(2'b0), .io_axi_AW_AWPROT(3'b0),
    .io_axi_W_WDATA(cpu_wdata), .io_axi_W_WSTRB(cpu_wstrb), .io_axi_W_WLAST(cpu_wlast),
    .io_axi_W_WVALID(cpu_wvalid), .io_axi_W_WREADY(cpu_wready),
    .io_axi_B_BVALID(cpu_bvalid), .io_axi_B_BREADY(cpu_bready),
    .io_axi_B_BRESP(cpu_bresp), .io_axi_B_BID(cpu_bid),
    .io_axi_AR_ARVALID(cpu_arvalid), .io_axi_AR_ARREADY(cpu_arready),
    .io_axi_AR_ARADDR(cpu_araddr),
    .io_axi_AR_ARID(4'b0), .io_axi_AR_ARLEN(8'b0), .io_axi_AR_ARSIZE(3'b0),
    .io_axi_AR_ARBURST(2'b0), .io_axi_AR_ARPROT(3'b0),
    .io_axi_R_RVALID(cpu_rvalid), .io_axi_R_RREADY(cpu_rready),
    .io_axi_R_RDATA(cpu_rdata), .io_axi_R_RRESP(cpu_rresp),
    .io_axi_R_RLAST(cpu_rlast), .io_axi_R_RID(cpu_rid)
  );
endmodule
